FROM postgres:17-alpine

LABEL maintainer="Alon Mell"
LABEL description="PostgreSQL for testing migrator"
LABEL version="1.0"

ENV POSTGRES_USER=test
ENV POSTGRES_PASSWORD=test
ENV POSTGRES_DB=testdb

EXPOSE 5432